apiVersion: batch/v1
kind: CronJob
metadata:
  name: gogoscraper
spec:
  schedule: "45 22 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gogoscraper
            image: tsafacjo/jumia-car-scrap:0.92
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: scrapper
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
               secretKeyRef:
                 name: scrapper
                 key: AWS_SECRET_ACCESS_KEY 
          restartPolicy: OnFailure
